name: my-pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Elastic Beanstalk CLI version
      - name: Get EB CLI version
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2

      - name: Deploying docker compose
        run: |
          eb init -p docker voting-app

      # Create the Elastic Beanstalk environment
      - name: Create test environment
        run: |
          eb create demo-environment
      
      - name: Deploying docker compose
        run: |
          eb open demo-environment

     


